### ISSUE TITLE
Lada dataset. Confusion with regard to trimmed/untrimmed versions of the dataset

### ISSUE THREAD

**Issue by taras-sereda** [egorsmkv/ukrainian-tts-datasets#13]
Hi, it's good to see UA speech datasets are getting larger!

At the moment I'm experimenting with Lada dataset, and it has 2 versions trimmed and untrimmed.
I have a questions, what's the intended use case for untrimmed data?
Wouldn't it be sufficient to keep only trimmed version of the corpora?

Same applies to various sample rates. As a suggestion it should be sufficient to keep single sample rate, say the highest one.

**Comment by egorsmkv** [comment]
Hello!

> I have a questions, what's the intended use case for untrimmed data?

I have chose just to keep the original data, without any edits. Maybe someone will need to do what they want with it.

> Same applies to various sample rates. As a suggestion it should be sufficient to keep single sample rate, say the highest one.

I have been using it in educational presentations so it's just useful to use the dataset faster.
