### ISSUE TITLE
Test with dataset tetyana

### ISSUE THREAD

**Issue by magicse** [egorsmkv/ukrainian-tts-datasets#2]
Training test with dataset tetyana without correct stress in words.
[ukr_test_40_28.zip](https://github.com/user-attachments/files/16836727/ukr_test_40_28.zip)

**Comment by egorsmkv** [comment]
It's intelligible, what do you use to make it?

**Comment by magicse** [comment]
StyleTTS and the size of the model came out to be about 311 MB

**Comment by patriotyk** [comment]
@magicse  Do you speak ukrainian? For what reason do you train it?

**Comment by magicse** [comment]
Yes. I try to get more quality of voice. And may be in future try port it to embedded devices like orange Pi .

**Comment by magicse** [comment]
Yes. I try to get more quality of voice. And may be in future try port it to embedded devices like orange Pi for local voice assistant.

**Comment by egorsmkv** [comment]
@magicse then join our community here - https://t.me/speech_synthesis_uk

**Comment by magicse** [comment]
Hi @egorsmkv 
Test with StyleTTS https://huggingface.co/spaces/tracert/ukr-tts size of model 160 mb only.
I use espeak- ng for phonemisation and stress... but every new version of espeak  has problems with Ukrainian language, because someone make incorrect changes of rules and dictionary in espeak github repo. And my local espeak and hugginface espeak work with different rules )))
That is why I want try to use ipa-uk and  [ukrainian-word-stress](https://github.com/lang-uk/ukrainian-word-stress) but there are some problems with it.
https://github.com/lang-uk/ukrainian-word-stress/issues/7#issue-2551661934
The main task is to get a high-quality voice with a small model size. After that, I will try to transfer it all to cpp.
I have already moved Hifi-GAN to cpp https://github.com/magicse/ncnn-hifi-GAN
